[project]
name = "mymediavault-vm-worker"
version = "0.1.0"
description = "VM-hosted torrent metadata and preview worker for MyMediaVault"
readme = "README.md"
authors = [
    { name = "Co2Link", email = "Co2Link@users.noreply.github.com" }
]
requires-python = ">=3.13,<3.14"
dependencies = [
    "beanie>=2.1.0",
    "boto3>=1.43.9",
    "libtorrent>=2.0.11",
    "pydantic-settings>=2.14.1",
    "pymongo>=4.17.0",
    "torrent-preview==5.2.6",
]

[dependency-groups]
dev = [
    "pytest>=9.0.3",
]

[project.scripts]
mymediavault-vm-worker = "mymediavault_vm_worker:main"

[build-system]
requires = ["uv_build>=0.11.14,<0.12.0"]
build-backend = "uv_build"

[[tool.uv.index]]
name = "lingxt"
url = "https://pkgs.dev.azure.com/lingxt/_packaging/lingxt/pypi/simple/"
explicit = true

[tool.uv.sources]
torrent-preview = { index = "lingxt" }
