version: "3.9"

services:
  devcontainer:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    ports:
      - "4500:4500" # For codex app-server
    volumes:
      - ../..:/workspaces:cached
      - claude:/home/vscode/.claude
      - codex:/home/vscode/.codex
      - gemini:/home/vscode/.gemini
      - uv-cache:/root/.cache/uv
    command: sleep infinity
    networks:
      - devnet
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite:latest
    restart: unless-stopped
    command: azurite --blobHost 0.0.0.0 --queueHost 0.0.0.0 --skipApiVersionCheck --location /data
    volumes:
      - azurite-data:/data
    network_mode: service:devcontainer
  mongo:
    image: mongo:latest
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
      - config_db:/data/configdb
    network_mode: service:devcontainer
volumes:
  claude:
  codex:
  gemini:
  uv-cache:
  azurite-data:
  mongo-data:
  config_db:

networks:
  devnet:
